# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Zuentec.ORDNA
PackageVersion: 0.38.1
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Ollama.Ollama
ProductCode: '{4F896AB9-D68C-45C8-9BE0-7C15037C4352}_is1'
AppsAndFeaturesEntries:
- DisplayName: ORDNA 0.38.1
  Publisher: Eckehard Zündorf
  ProductCode: '{4F896AB9-D68C-45C8-9BE0-7C15037C4352}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://zuentec.de/download/ORDNA-0.38.1-Setup.exe
  InstallerSha256: 863868513264726D5EFBF7B2919AD3C89208DEB5CD3D01EE83151A762E54153C
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-30
